name: Build
on: [push]
jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: brew install automake
      - run: autoreconf -i
      - run: ./configure --enable-warning-as-error
      - run: make all
      - run: make dist
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: autoreconf -i
      - run: ./configure --enable-warning-as-error
      - run: make all
      - run: make dist
  build-win:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc autoconf automake make
      - run: autoreconf -i
      - run: ./configure --enable-warning-as-error
      - run: make all
      - run: make dist

